spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  datasource:
    generate-unique-name: false
  profiles:
    active:
      - dev
---
  profiles: prod
---
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update