spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  profiles:
    active:
      - dev
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    database-change-log-lock-table: false
logging:
  level:
    liquibase: info
    org.springframework.web: debug
  file:
    name: ws.log
---
  profiles: test
---
  profiles: prod
---
  profiles: dev
  spring:
    datasource:
      generate-unique-name: false
      url: jdbc:h2:./devdb
      username: sa
    jpa:
      hibernate:
        ddl-auto: update
